CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(64) PRIMARY KEY,
  email VARCHAR(190) NOT NULL UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  name VARCHAR(190) NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'admin',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS authors (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  avatar TEXT NULL,
  bio TEXT NULL,
  userId VARCHAR(64) NULL UNIQUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_authors_user FOREIGN KEY (userId) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS categories (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  slug VARCHAR(190) NOT NULL UNIQUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS tags (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  slug VARCHAR(190) NOT NULL UNIQUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS articles (
  id VARCHAR(64) PRIMARY KEY,
  slug VARCHAR(220) NOT NULL UNIQUE,
  title TEXT NOT NULL,
  `lead` TEXT NOT NULL,
  body LONGTEXT NOT NULL,
  coverImage TEXT NULL,
  coverCaption TEXT NULL,
  categoryId VARCHAR(64) NOT NULL,
  city VARCHAR(64) NOT NULL,
  authorId VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  isBreaking TINYINT(1) NOT NULL DEFAULT 0,
  isFeatured TINYINT(1) NOT NULL DEFAULT 0,
  publishedAt DATETIME NULL,
  viewCount INT NOT NULL DEFAULT 0,
  readingTimeMin INT NOT NULL DEFAULT 3,
  sourceUrl TEXT NULL,
  sourceName VARCHAR(190) NULL,
  importSchema LONGTEXT NULL,
  seoTitle TEXT NULL,
  seoDescription TEXT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_articles_category FOREIGN KEY (categoryId) REFERENCES categories(id),
  CONSTRAINT fk_articles_author FOREIGN KEY (authorId) REFERENCES authors(id)
);
CREATE INDEX idx_articles_status_published ON articles(status, publishedAt);
CREATE INDEX idx_articles_city ON articles(city);
CREATE INDEX idx_articles_breaking ON articles(isBreaking);
CREATE INDEX idx_articles_featured ON articles(isFeatured);
CREATE TABLE IF NOT EXISTS article_tags (
  articleId VARCHAR(64) NOT NULL,
  tagId VARCHAR(64) NOT NULL,
  PRIMARY KEY (articleId, tagId),
  CONSTRAINT fk_article_tags_article FOREIGN KEY (articleId) REFERENCES articles(id) ON DELETE CASCADE,
  CONSTRAINT fk_article_tags_tag FOREIGN KEY (tagId) REFERENCES tags(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS comments (
  id VARCHAR(64) PRIMARY KEY,
  articleId VARCHAR(64) NOT NULL,
  name VARCHAR(190) NOT NULL,
  body TEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_comments_article FOREIGN KEY (articleId) REFERENCES articles(id) ON DELETE CASCADE
);
CREATE INDEX idx_comments_article_status ON comments(articleId, status);
CREATE TABLE IF NOT EXISTS polls (
  id VARCHAR(64) PRIMARY KEY,
  question TEXT NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS poll_options (
  id VARCHAR(64) PRIMARY KEY,
  pollId VARCHAR(64) NOT NULL,
  text TEXT NOT NULL,
  CONSTRAINT fk_poll_options_poll FOREIGN KEY (pollId) REFERENCES polls(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS poll_votes (
  id VARCHAR(64) PRIMARY KEY,
  pollOptionId VARCHAR(64) NOT NULL,
  ipHash VARCHAR(190) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_poll_votes (pollOptionId, ipHash),
  CONSTRAINT fk_poll_votes_option FOREIGN KEY (pollOptionId) REFERENCES poll_options(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS videos (
  id VARCHAR(64) PRIMARY KEY,
  title TEXT NOT NULL,
  youtubeId VARCHAR(64) NULL,
  videoUrl TEXT NULL,
  duration VARCHAR(32) NULL,
  thumbnail TEXT NULL,
  viewCount INT NOT NULL DEFAULT 0,
  publishedAt DATETIME NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id VARCHAR(64) PRIMARY KEY,
  email VARCHAR(190) NOT NULL UNIQUE,
  confirmed TINYINT(1) NOT NULL DEFAULT 0,
  token VARCHAR(190) NOT NULL UNIQUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS reader_submissions (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  contact VARCHAR(190) NOT NULL,
  message TEXT NOT NULL,
  attachments JSON NOT NULL,
  `read` TINYINT(1) NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- restorani modul
CREATE TABLE IF NOT EXISTS restaurants (
  id VARCHAR(64) PRIMARY KEY,
  ownerId VARCHAR(64) NULL,
  name VARCHAR(190) NOT NULL,
  slug VARCHAR(220) NOT NULL UNIQUE,
  city VARCHAR(64) NOT NULL,
  address TEXT NULL,
  phone VARCHAR(64) NULL,
  whatsapp VARCHAR(64) NULL,
  description TEXT NULL,
  logoImage TEXT NULL,
  coverImage TEXT NULL,
  hoursJson JSON NULL,
  menuLangsJson JSON NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  qrCode VARCHAR(64) NULL,
  reviewsEnabled TINYINT(1) NOT NULL DEFAULT 1,
  avgRating DECIMAL(3,1) NULL,
  reviewCount INT NOT NULL DEFAULT 0,
  viewCount INT NOT NULL DEFAULT 0,
  publishedAt DATETIME NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS menu_categories (
  id VARCHAR(64) PRIMARY KEY,
  restaurantId VARCHAR(64) NOT NULL,
  name VARCHAR(190) NOT NULL,
  translationsJson JSON NULL,
  sortOrder INT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_menu_categories_rest FOREIGN KEY (restaurantId) REFERENCES restaurants(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS menu_items (
  id VARCHAR(64) PRIMARY KEY,
  categoryId VARCHAR(64) NOT NULL,
  restaurantId VARCHAR(64) NOT NULL,
  name VARCHAR(190) NOT NULL,
  description TEXT NULL,
  price DECIMAL(10,2) NULL,
  priceLabel VARCHAR(190) NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'RSD',
  image TEXT NULL,
  tagsJson JSON NULL,
  translationsJson JSON NULL,
  isAvailable TINYINT(1) NOT NULL DEFAULT 1,
  sortOrder INT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_menu_items_cat FOREIGN KEY (categoryId) REFERENCES menu_categories(id) ON DELETE CASCADE,
  CONSTRAINT fk_menu_items_rest FOREIGN KEY (restaurantId) REFERENCES restaurants(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS restaurant_reviews (
  id VARCHAR(64) PRIMARY KEY,
  restaurantId VARCHAR(64) NOT NULL,
  name VARCHAR(190) NOT NULL,
  rating INT NOT NULL,
  body TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rest_reviews_rest FOREIGN KEY (restaurantId) REFERENCES restaurants(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS auto_vesti_settings (
  settingKey VARCHAR(128) PRIMARY KEY,
  value LONGTEXT NOT NULL,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
