<?php

return [
    [
        'slug' => 'novi-pazar-regionalni-centar-za-mlade',
        'title' => 'Novi Pazar dobija regionalni centar za mlade: izgradnja vrijedna pet miliona eura',
        'lead' => 'Projekat obuhvata edukativni centar, sportsku dvoranu i prostor za startape. Završetak radova najavljen je za proljeće 2027. godine.',
        'body' => <<<'BODY'
Gradonačelnik Novog Pazara potpisao je danas ugovor o izgradnji regionalnog centra za mlade.

Projekat, vrijedan pet miliona eura, finansira se iz gradskog budžeta, sredstava republičke vlade i donacija međunarodnih partnera.

> Ovo nije samo zgrada — ovo je poruka mladima da njihova budućnost može biti ovdje.

U sklopu centra planiran je edukativni blok sa učionicama i IT laboratorijama, višenamjenska sportska dvorana i koworking prostor za startape.
BODY,
        'categorySlug' => 'drustvo',
        'city' => 'NOVI_PAZAR',
        'authorName' => 'Emina Destanović',
        'isFeatured' => true,
        'isBreaking' => true,
        'hoursAgo' => 0.5,
        'viewCount' => 4200,
        'tags' => ['NoviPazar', 'mladi', 'investicije'],
    ],
    [
        'slug' => 'pestera-visoravan-turizam',
        'title' => 'Pešterska visoravan među pet destinacija koje preporučuju evropski turistički vodiči',
        'lead' => 'Međunarodni portal istakao je prirodne ljepote i autentičnu gastronomiju Peštera kao jednu od najboljih ruralnih destinacija na Balkanu.',
        'body' => 'Turistički vodiči posebno ističu visoravan, lokalne sirane i planinarske rute koje povezuju Sjenicu sa okolnim selima.',
        'categorySlug' => 'vijesti',
        'city' => 'SJENICA',
        'authorName' => 'Redakcija',
        'hoursAgo' => 1,
        'viewCount' => 3100,
        'tags' => ['Pešter', 'turizam'],
    ],
    [
        'slug' => 'novi-paviljon-univerziteta',
        'title' => 'Otvoren novi paviljon Univerziteta: 400 studenata dobija savremene laboratorije',
        'lead' => 'Rektorat najavljuje proširenje programa u oblasti IT-a i biomedicinskih nauka već od jeseni.',
        'body' => 'Investicija vrijedna 2,3 miliona eura realizovana je u saradnji sa partnerskim fakultetima iz regiona.',
        'categorySlug' => 'drustvo',
        'city' => 'NOVI_PAZAR',
        'authorName' => 'Emina Destanović',
        'hoursAgo' => 2,
        'viewCount' => 2800,
        'tags' => ['obrazovanje', 'univerzitet'],
    ],
    [
        'slug' => 'sajam-privrede-tutin',
        'title' => 'Sajam privrede okupio rekordnih 120 izlagača iz regiona i dijaspore',
        'lead' => 'Trodnevni sajam u Tutinu zabilježio je porast broja posjetilaca u odnosu na prošlu godinu.',
        'body' => 'Organizatori ističu da su posebno zastupljene zanatske radnje i prehrambena industrija.',
        'categorySlug' => 'ekonomija',
        'city' => 'TUTIN',
        'authorName' => 'Selma Hadžić',
        'hoursAgo' => 3,
        'viewCount' => 1900,
        'tags' => ['privreda', 'sajam'],
    ],
    [
        'slug' => 'limska-regata-prijepolje',
        'title' => 'Limska regata ove godine očekuje više od dvije hiljade učesnika',
        'lead' => 'Organizatori najavljuju proširenu trasu i dodatne sigurnosne mjere na rijeci Lim.',
        'body' => 'Regata će se održati krajem jula, a prijave su već otvorene za timove iz cijelog regiona.',
        'categorySlug' => 'hronika',
        'city' => 'PRIJEPOLJE',
        'authorName' => 'Redakcija',
        'isBreaking' => true,
        'hoursAgo' => 4,
        'viewCount' => 2400,
        'tags' => ['Lim', 'sport'],
    ],
    [
        'slug' => 'fk-novi-pazar-utakmica-sezone',
        'title' => 'FK Novi Pazar pred utakmicom sezone: navijači spremaju spektakl',
        'lead' => 'Gradski stadion očekuje pun kapacitet večeras, a klub poziva navijače na raniji dolazak.',
        'body' => 'Trener poručuje da je ekipa spremna i da će dati maksimum u borbi za plasman.',
        'categorySlug' => 'sport',
        'city' => 'NOVI_PAZAR',
        'authorName' => 'Amir Kovačević',
        'isBreaking' => true,
        'hoursAgo' => 1,
        'viewCount' => 5600,
        'tags' => ['fudbal', 'NoviPazar'],
    ],
    [
        'slug' => 'mladi-rukometasi-plasman',
        'title' => 'Mladi rukometaši izborili plasman na završni turnir',
        'lead' => 'Selekcija U17 ostvarila je historijski uspjeh na republičkom prvenstvu.',
        'body' => 'Finale se igra u subotu u Novom Pazaru pred očekivanim punim tribinama.',
        'categorySlug' => 'sport',
        'city' => 'TUTIN',
        'authorName' => 'Amir Kovačević',
        'hoursAgo' => 6,
        'viewCount' => 1200,
        'tags' => ['rukomet'],
    ],
    [
        'slug' => 'dijaspora-luksemburg-humanitarno',
        'title' => 'Sandžaklije u Luksemburgu organizovale humanitarno veče: prikupljeno 40.000 eura',
        'lead' => 'Sredstva će biti usmjerena za školske stipendije i zdravstvenu pomoć u tri opštine.',
        'body' => 'Organizatori najavljuju i online aukciju za mlade preduzetnike iz regiona.',
        'categorySlug' => 'dijaspora',
        'city' => 'OTHER',
        'authorName' => 'Redakcija',
        'hoursAgo' => 2,
        'viewCount' => 3400,
        'tags' => ['dijaspora', 'humanitarno'],
    ],
    [
        'slug' => 'direktne-avio-linije',
        'title' => 'Direktne avio-linije ka Istanbulu i Beču: šta to znači za region',
        'lead' => 'Analitičari smatraju da bi povezivanje moglo povećati turistički promet i poslovne kontakte.',
        'body' => 'Prvi letovi bi, prema najavama, mogli biti uvedeni već naredne sezone.',
        'categorySlug' => 'dijaspora',
        'city' => 'NOVI_PAZAR',
        'authorName' => 'Selma Hadžić',
        'hoursAgo' => 8,
        'viewCount' => 2100,
        'tags' => ['saobraćaj', 'dijaspora'],
    ],
    [
        'slug' => 'vodovodna-mreza-investicija',
        'title' => 'Velika investicija u vodovodnu mrežu: radovi u sedam mjesnih zajednica',
        'lead' => 'Projekat vrijedan 8 miliona evra trebao bi riješiti decenijski problem snabdijevanja vodom.',
        'body' => 'Prvi rovovi kopaju se već naredne sedmice u okolini Sjenice.',
        'categorySlug' => 'politika',
        'city' => 'SJENICA',
        'authorName' => 'Redakcija',
        'hoursAgo' => 5,
        'viewCount' => 12400,
        'tags' => ['infrastruktura', 'voda'],
    ],
    [
        'slug' => 'sjenicki-sir-zasticeno-porijeklo',
        'title' => 'Sjenički sir dobio zaštićeno geografsko porijeklo na nivou EU',
        'lead' => 'Proizvođači očekuju bolju plasmanu na evropskom tržištu i veće cijene.',
        'body' => 'Certifikacija je rezultat višegodišnjeg rada lokalnih udruženja i inspekcija.',
        'categorySlug' => 'ekonomija',
        'city' => 'SJENICA',
        'authorName' => 'Selma Hadžić',
        'hoursAgo' => 7,
        'viewCount' => 9800,
        'tags' => ['sir', 'EU'],
    ],
    [
        'slug' => 'ljetne-manifestacije-raspored',
        'title' => 'Raspored ljetnih manifestacija: šta nas očekuje u julu i augustu',
        'lead' => 'Od dana borovnice do noćnog bazara — pregled najvažnijih događaja u regionu.',
        'body' => 'Organizatori najavljuju i nove kulturne programe za mlade.',
        'categorySlug' => 'kultura',
        'city' => 'NOVA_VAROS',
        'authorName' => 'Redakcija',
        'hoursAgo' => 10,
        'viewCount' => 7100,
        'tags' => ['kultura', 'manifestacije'],
    ],
    [
        'slug' => 'dijaspora-fabrike-radna-mjesta',
        'title' => 'Dijaspora ulaže u zavičaj: tri nove fabrike otvaraju 600 radnih mjesta',
        'lead' => 'Investitori iz Austrije i Njemačke potpisali su memorandume sa lokalnim vlastima.',
        'body' => 'Prva fabrika bi mogla početi sa radom već u oktobru.',
        'categorySlug' => 'ekonomija',
        'city' => 'PRIJEPOLJE',
        'authorName' => 'Selma Hadžić',
        'hoursAgo' => 12,
        'viewCount' => 6500,
        'tags' => ['investicije', 'dijaspora'],
    ],
    [
        'slug' => 'gradsko-vijece-budzet',
        'title' => 'Gradsko vijeće usvojilo budžet za narednu godinu',
        'lead' => 'Prioriteti su infrastruktura, obrazovanje i podrška malim preduzetnicima.',
        'body' => 'Opozicija je tražila veća sredstva za zdravstvo, ali je predlog usvojen većinom glasova.',
        'categorySlug' => 'politika',
        'city' => 'NOVI_PAZAR',
        'authorName' => 'Redakcija',
        'isBreaking' => true,
        'hoursAgo' => 3,
        'viewCount' => 1800,
        'tags' => ['budžet', 'politika'],
    ],
    [
        'slug' => 'magistralni-put-rekonstrukcija',
        'title' => 'Počela rekonstrukcija magistralnog puta Novi Pazar — Sjenica',
        'lead' => 'Radovi će trajati najmanje šest mjeseci, a saobraćaj je preusmjeren na alternativne rute.',
        'body' => 'Investitor garantuje da će glavni dionice biti završene prije zimskog perioda.',
        'categorySlug' => 'hronika',
        'city' => 'SJENICA',
        'authorName' => 'Redakcija',
        'isBreaking' => true,
        'hoursAgo' => 2,
        'viewCount' => 3200,
        'tags' => ['putevi', 'saobraćaj'],
    ],
    [
        'slug' => 'dani-borovnice-nova-varos',
        'title' => 'Manifestacija "Dani borovnice" privukla posjetioce iz cijelog regiona',
        'lead' => 'Trodnevni program uključivao je degustacije, koncerte i izložbu lokalnih zanatlija.',
        'body' => 'Organizatori najavljuju još veći festival naredne godine.',
        'categorySlug' => 'kultura',
        'city' => 'NOVA_VAROS',
        'authorName' => 'Redakcija',
        'hoursAgo' => 5,
        'viewCount' => 900,
        'tags' => ['borovnica', 'festival'],
    ],
    [
        'slug' => 'autobuski-polasci-sarajevo-istanbul',
        'title' => 'Novi autobuski polasci ka Sarajevu i Istanbulu od jula',
        'lead' => 'Prevoznik najavljuje dnevne linije i povoljnije cijene za studente i penzionere.',
        'body' => 'Karte će biti dostupne online i na šalterima u tri grada.',
        'categorySlug' => 'vijesti',
        'city' => 'NOVI_PAZAR',
        'authorName' => 'Redakcija',
        'hoursAgo' => 6,
        'viewCount' => 1100,
        'tags' => ['saobraćaj'],
    ],
    [
        'slug' => 'priboj-solarna-elektrana',
        'title' => 'U Priboju puštena u rad solarna elektrana snage 5 MW',
        'lead' => 'Elektrana će opsluživati dio industrijske zone i smanjiti troškove lokalnih firmi.',
        'body' => 'Investicija je realizovana u partnerstvu sa regionalnim energetskim kompanijama.',
        'categorySlug' => 'ekonomija',
        'city' => 'PRIBOJ',
        'authorName' => 'Selma Hadžić',
        'hoursAgo' => 9,
        'viewCount' => 800,
        'tags' => ['energija', 'zelena tranzicija'],
    ],
    [
        'slug' => 'rozaje-kulturni-centar',
        'title' => 'Otvoren obnovljeni kulturni centar u Rožajama',
        'lead' => 'Centar nudi nove scene za pozorište, kino i edukativne radionice za mlade.',
        'body' => 'Renoviranje je trajalo dvije godine uz podršku donatora iz regiona.',
        'categorySlug' => 'kultura',
        'city' => 'ROZAJE',
        'authorName' => 'Redakcija',
        'hoursAgo' => 14,
        'viewCount' => 750,
        'tags' => ['kultura', 'Rožaje'],
    ],
    [
        'slug' => 'berane-zdravstveni-dan',
        'title' => 'Besplatni zdravstveni pregledi u Beranama: veliki interes građana',
        'lead' => 'Akcija obuhvata preventivne preglede i savjetovanje o hroničnim bolestima.',
        'body' => 'Ljekari pozivaju građane da iskoriste priliku za ranu dijagnostiku.',
        'categorySlug' => 'drustvo',
        'city' => 'BERANE',
        'authorName' => 'Emina Destanović',
        'hoursAgo' => 11,
        'viewCount' => 600,
        'tags' => ['zdravstvo'],
    ],
];
